#!/bin/bash


launch() {
    killall polybar
    #conky_launch
    sleep 0.2
    # polybar -c /home/knoxtrot/edits/dotfiles/.config/polybar/config bar & 
    polybar top &
    #if type "xrandr"; then
    #for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    #    MONITOR=$m polybar --reload example &
    #done
    #else
    #  polybar --reload example &
    #fi
    BAR_ID=$!
    rm -f /tmp/polybar_mqueue_top
    ln -s /tmp/polybar_mqueue.$BAR_ID /tmp/polybar_mqueue_top
}


case "$1" in
	launch)
		launch;;
	show)
		echo "for the sake of case";;
esac
